name: ReleaseAddon
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r plugin.retrowave.indrajith.zip . -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - uses: paulhatch/semantic-version@v4.0.2
      id: version_name
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        change_path: "./"
        namespace: retrowave
        short_tags: true
        bump_each_commit: false
    - uses: "marvinpinto/action-automatic-releases@latest"
      id: create_release
      with:
        repo_token: "${{ secrets.TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          *.zip
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPO_OWNER: cooljith91112
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: plugin.retrowave.indrajith.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}